version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8003:80
    container_name: adquisiciones_app
    restart: always
    extra_hosts:
    - "dockerhost:host-gateway"
    volumes:
      - .:/var/www/html/planillas
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
